sudo: required

language: python
python:
  - "3.4"  # python3 on ubuntu 14.04

services:
  - docker

before_install:
  - sudo mkdir -p /var/lib/kastenwesen/
  - sudo chown -R root:docker /var/lib/kastenwesen/
  - sudo chmod -R g+rwX /var/lib/kastenwesen/

install:
  - pip install -r requirements.txt

script:
  - ./example-config/run_tests.py
